=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/api_model_base'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/action_ref'
require 'openapi_client/models/decision_apply_request'
require 'openapi_client/models/decision_apply_response'
require 'openapi_client/models/decision_approve_request'
require 'openapi_client/models/decision_approve_response'
require 'openapi_client/models/decision_propose_request'
require 'openapi_client/models/decision_propose_response'
require 'openapi_client/models/error_response'
require 'openapi_client/models/error_response_error'
require 'openapi_client/models/health_response'
require 'openapi_client/models/policy_evaluate_request'
require 'openapi_client/models/policy_evaluate_response'

# APIs
require 'openapi_client/api/decisions_api'
require 'openapi_client/api/health_api'
require 'openapi_client/api/policy_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
