=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class DecisionApplyResponse < ApiModelBase
    attr_accessor :trace_id

    attr_accessor :decision_id

    attr_accessor :decision_status

    attr_accessor :decision_kind

    attr_accessor :blocked_reason

    attr_accessor :actions

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'trace_id' => :'trace_id',
        :'decision_id' => :'decision_id',
        :'decision_status' => :'decision_status',
        :'decision_kind' => :'decision_kind',
        :'blocked_reason' => :'blocked_reason',
        :'actions' => :'actions'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'trace_id' => :'String',
        :'decision_id' => :'Integer',
        :'decision_status' => :'String',
        :'decision_kind' => :'String',
        :'blocked_reason' => :'String',
        :'actions' => :'Array<ActionRef>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::DecisionApplyResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::DecisionApplyResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'trace_id')
        self.trace_id = attributes[:'trace_id']
      else
        self.trace_id = nil
      end

      if attributes.key?(:'decision_id')
        self.decision_id = attributes[:'decision_id']
      else
        self.decision_id = nil
      end

      if attributes.key?(:'decision_status')
        self.decision_status = attributes[:'decision_status']
      end

      if attributes.key?(:'decision_kind')
        self.decision_kind = attributes[:'decision_kind']
      end

      if attributes.key?(:'blocked_reason')
        self.blocked_reason = attributes[:'blocked_reason']
      end

      if attributes.key?(:'actions')
        if (value = attributes[:'actions']).is_a?(Array)
          self.actions = value
        end
      else
        self.actions = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @trace_id.nil?
        invalid_properties.push('invalid value for "trace_id", trace_id cannot be nil.')
      end

      if @decision_id.nil?
        invalid_properties.push('invalid value for "decision_id", decision_id cannot be nil.')
      end

      if @actions.nil?
        invalid_properties.push('invalid value for "actions", actions cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @trace_id.nil?
      return false if @decision_id.nil?
      return false if @actions.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] trace_id Value to be assigned
    def trace_id=(trace_id)
      if trace_id.nil?
        fail ArgumentError, 'trace_id cannot be nil'
      end

      @trace_id = trace_id
    end

    # Custom attribute writer method with validation
    # @param [Object] decision_id Value to be assigned
    def decision_id=(decision_id)
      if decision_id.nil?
        fail ArgumentError, 'decision_id cannot be nil'
      end

      @decision_id = decision_id
    end

    # Custom attribute writer method with validation
    # @param [Object] actions Value to be assigned
    def actions=(actions)
      if actions.nil?
        fail ArgumentError, 'actions cannot be nil'
      end

      @actions = actions
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          trace_id == o.trace_id &&
          decision_id == o.decision_id &&
          decision_status == o.decision_status &&
          decision_kind == o.decision_kind &&
          blocked_reason == o.blocked_reason &&
          actions == o.actions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [trace_id, decision_id, decision_status, decision_kind, blocked_reason, actions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
