=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class DecisionApplyRequest < ApiModelBase
    attr_accessor :run_id

    attr_accessor :action_type

    attr_accessor :action_scope

    attr_accessor :target_evidence_asset_id

    attr_accessor :plan_evidence_asset_id

    attr_accessor :budget_currency

    attr_accessor :budget_estimate_amount

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'run_id' => :'run_id',
        :'action_type' => :'action_type',
        :'action_scope' => :'action_scope',
        :'target_evidence_asset_id' => :'target_evidence_asset_id',
        :'plan_evidence_asset_id' => :'plan_evidence_asset_id',
        :'budget_currency' => :'budget_currency',
        :'budget_estimate_amount' => :'budget_estimate_amount'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'run_id' => :'String',
        :'action_type' => :'String',
        :'action_scope' => :'String',
        :'target_evidence_asset_id' => :'Integer',
        :'plan_evidence_asset_id' => :'Integer',
        :'budget_currency' => :'String',
        :'budget_estimate_amount' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::DecisionApplyRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::DecisionApplyRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'run_id')
        self.run_id = attributes[:'run_id']
      else
        self.run_id = nil
      end

      if attributes.key?(:'action_type')
        self.action_type = attributes[:'action_type']
      end

      if attributes.key?(:'action_scope')
        self.action_scope = attributes[:'action_scope']
      end

      if attributes.key?(:'target_evidence_asset_id')
        self.target_evidence_asset_id = attributes[:'target_evidence_asset_id']
      else
        self.target_evidence_asset_id = nil
      end

      if attributes.key?(:'plan_evidence_asset_id')
        self.plan_evidence_asset_id = attributes[:'plan_evidence_asset_id']
      else
        self.plan_evidence_asset_id = nil
      end

      if attributes.key?(:'budget_currency')
        self.budget_currency = attributes[:'budget_currency']
      end

      if attributes.key?(:'budget_estimate_amount')
        self.budget_estimate_amount = attributes[:'budget_estimate_amount']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @run_id.nil?
        invalid_properties.push('invalid value for "run_id", run_id cannot be nil.')
      end

      if @target_evidence_asset_id.nil?
        invalid_properties.push('invalid value for "target_evidence_asset_id", target_evidence_asset_id cannot be nil.')
      end

      if @plan_evidence_asset_id.nil?
        invalid_properties.push('invalid value for "plan_evidence_asset_id", plan_evidence_asset_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @run_id.nil?
      return false if @target_evidence_asset_id.nil?
      return false if @plan_evidence_asset_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] run_id Value to be assigned
    def run_id=(run_id)
      if run_id.nil?
        fail ArgumentError, 'run_id cannot be nil'
      end

      @run_id = run_id
    end

    # Custom attribute writer method with validation
    # @param [Object] target_evidence_asset_id Value to be assigned
    def target_evidence_asset_id=(target_evidence_asset_id)
      if target_evidence_asset_id.nil?
        fail ArgumentError, 'target_evidence_asset_id cannot be nil'
      end

      @target_evidence_asset_id = target_evidence_asset_id
    end

    # Custom attribute writer method with validation
    # @param [Object] plan_evidence_asset_id Value to be assigned
    def plan_evidence_asset_id=(plan_evidence_asset_id)
      if plan_evidence_asset_id.nil?
        fail ArgumentError, 'plan_evidence_asset_id cannot be nil'
      end

      @plan_evidence_asset_id = plan_evidence_asset_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          run_id == o.run_id &&
          action_type == o.action_type &&
          action_scope == o.action_scope &&
          target_evidence_asset_id == o.target_evidence_asset_id &&
          plan_evidence_asset_id == o.plan_evidence_asset_id &&
          budget_currency == o.budget_currency &&
          budget_estimate_amount == o.budget_estimate_amount
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [run_id, action_type, action_scope, target_evidence_asset_id, plan_evidence_asset_id, budget_currency, budget_estimate_amount].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
