=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class EvidenceAsset < ApiModelBase
    attr_accessor :id

    attr_accessor :project_id

    attr_accessor :evidence_ref

    attr_accessor :media_type

    attr_accessor :source_kind

    attr_accessor :source_uri

    attr_accessor :content_sha256

    attr_accessor :content_length

    attr_accessor :mime_type

    attr_accessor :language

    attr_accessor :retention_policy

    attr_accessor :expires_at_utc

    attr_accessor :status

    attr_accessor :created_by_type

    attr_accessor :created_by_id

    attr_accessor :created_at

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'project_id' => :'project_id',
        :'evidence_ref' => :'evidence_ref',
        :'media_type' => :'media_type',
        :'source_kind' => :'source_kind',
        :'source_uri' => :'source_uri',
        :'content_sha256' => :'content_sha256',
        :'content_length' => :'content_length',
        :'mime_type' => :'mime_type',
        :'language' => :'language',
        :'retention_policy' => :'retention_policy',
        :'expires_at_utc' => :'expires_at_utc',
        :'status' => :'status',
        :'created_by_type' => :'created_by_type',
        :'created_by_id' => :'created_by_id',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'project_id' => :'String',
        :'evidence_ref' => :'String',
        :'media_type' => :'String',
        :'source_kind' => :'String',
        :'source_uri' => :'String',
        :'content_sha256' => :'String',
        :'content_length' => :'Integer',
        :'mime_type' => :'String',
        :'language' => :'String',
        :'retention_policy' => :'String',
        :'expires_at_utc' => :'Time',
        :'status' => :'String',
        :'created_by_type' => :'String',
        :'created_by_id' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'source_uri',
        :'language',
        :'expires_at_utc',
        :'created_by_id',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::EvidenceAsset` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::EvidenceAsset`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      else
        self.project_id = nil
      end

      if attributes.key?(:'evidence_ref')
        self.evidence_ref = attributes[:'evidence_ref']
      else
        self.evidence_ref = nil
      end

      if attributes.key?(:'media_type')
        self.media_type = attributes[:'media_type']
      else
        self.media_type = nil
      end

      if attributes.key?(:'source_kind')
        self.source_kind = attributes[:'source_kind']
      else
        self.source_kind = nil
      end

      if attributes.key?(:'source_uri')
        self.source_uri = attributes[:'source_uri']
      end

      if attributes.key?(:'content_sha256')
        self.content_sha256 = attributes[:'content_sha256']
      else
        self.content_sha256 = nil
      end

      if attributes.key?(:'content_length')
        self.content_length = attributes[:'content_length']
      else
        self.content_length = nil
      end

      if attributes.key?(:'mime_type')
        self.mime_type = attributes[:'mime_type']
      else
        self.mime_type = nil
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'retention_policy')
        self.retention_policy = attributes[:'retention_policy']
      else
        self.retention_policy = nil
      end

      if attributes.key?(:'expires_at_utc')
        self.expires_at_utc = attributes[:'expires_at_utc']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'created_by_type')
        self.created_by_type = attributes[:'created_by_type']
      else
        self.created_by_type = nil
      end

      if attributes.key?(:'created_by_id')
        self.created_by_id = attributes[:'created_by_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @project_id.nil?
        invalid_properties.push('invalid value for "project_id", project_id cannot be nil.')
      end

      if @evidence_ref.nil?
        invalid_properties.push('invalid value for "evidence_ref", evidence_ref cannot be nil.')
      end

      if @media_type.nil?
        invalid_properties.push('invalid value for "media_type", media_type cannot be nil.')
      end

      if @source_kind.nil?
        invalid_properties.push('invalid value for "source_kind", source_kind cannot be nil.')
      end

      if @content_sha256.nil?
        invalid_properties.push('invalid value for "content_sha256", content_sha256 cannot be nil.')
      end

      if @content_sha256.to_s.length > 64
        invalid_properties.push('invalid value for "content_sha256", the character length must be smaller than or equal to 64.')
      end

      if @content_sha256.to_s.length < 64
        invalid_properties.push('invalid value for "content_sha256", the character length must be greater than or equal to 64.')
      end

      if @content_length.nil?
        invalid_properties.push('invalid value for "content_length", content_length cannot be nil.')
      end

      if @mime_type.nil?
        invalid_properties.push('invalid value for "mime_type", mime_type cannot be nil.')
      end

      if @retention_policy.nil?
        invalid_properties.push('invalid value for "retention_policy", retention_policy cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @created_by_type.nil?
        invalid_properties.push('invalid value for "created_by_type", created_by_type cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @project_id.nil?
      return false if @evidence_ref.nil?
      return false if @media_type.nil?
      media_type_validator = EnumAttributeValidator.new('String', ["text", "image", "audio", "video", "binary"])
      return false unless media_type_validator.valid?(@media_type)
      return false if @source_kind.nil?
      source_kind_validator = EnumAttributeValidator.new('String', ["pisag_fetch", "upload", "webhook", "generated", "import"])
      return false unless source_kind_validator.valid?(@source_kind)
      return false if @content_sha256.nil?
      return false if @content_sha256.to_s.length > 64
      return false if @content_sha256.to_s.length < 64
      return false if @content_length.nil?
      return false if @mime_type.nil?
      return false if @retention_policy.nil?
      retention_policy_validator = EnumAttributeValidator.new('String', ["short", "standard", "legal_hold"])
      return false unless retention_policy_validator.valid?(@retention_policy)
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["active", "expired", "tombstoned"])
      return false unless status_validator.valid?(@status)
      return false if @created_by_type.nil?
      created_by_type_validator = EnumAttributeValidator.new('String', ["system", "user", "service"])
      return false unless created_by_type_validator.valid?(@created_by_type)
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] project_id Value to be assigned
    def project_id=(project_id)
      if project_id.nil?
        fail ArgumentError, 'project_id cannot be nil'
      end

      @project_id = project_id
    end

    # Custom attribute writer method with validation
    # @param [Object] evidence_ref Value to be assigned
    def evidence_ref=(evidence_ref)
      if evidence_ref.nil?
        fail ArgumentError, 'evidence_ref cannot be nil'
      end

      @evidence_ref = evidence_ref
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] media_type Object to be assigned
    def media_type=(media_type)
      validator = EnumAttributeValidator.new('String', ["text", "image", "audio", "video", "binary"])
      unless validator.valid?(media_type)
        fail ArgumentError, "invalid value for \"media_type\", must be one of #{validator.allowable_values}."
      end
      @media_type = media_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] source_kind Object to be assigned
    def source_kind=(source_kind)
      validator = EnumAttributeValidator.new('String', ["pisag_fetch", "upload", "webhook", "generated", "import"])
      unless validator.valid?(source_kind)
        fail ArgumentError, "invalid value for \"source_kind\", must be one of #{validator.allowable_values}."
      end
      @source_kind = source_kind
    end

    # Custom attribute writer method with validation
    # @param [Object] content_sha256 Value to be assigned
    def content_sha256=(content_sha256)
      if content_sha256.nil?
        fail ArgumentError, 'content_sha256 cannot be nil'
      end

      if content_sha256.to_s.length > 64
        fail ArgumentError, 'invalid value for "content_sha256", the character length must be smaller than or equal to 64.'
      end

      if content_sha256.to_s.length < 64
        fail ArgumentError, 'invalid value for "content_sha256", the character length must be greater than or equal to 64.'
      end

      @content_sha256 = content_sha256
    end

    # Custom attribute writer method with validation
    # @param [Object] content_length Value to be assigned
    def content_length=(content_length)
      if content_length.nil?
        fail ArgumentError, 'content_length cannot be nil'
      end

      @content_length = content_length
    end

    # Custom attribute writer method with validation
    # @param [Object] mime_type Value to be assigned
    def mime_type=(mime_type)
      if mime_type.nil?
        fail ArgumentError, 'mime_type cannot be nil'
      end

      @mime_type = mime_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] retention_policy Object to be assigned
    def retention_policy=(retention_policy)
      validator = EnumAttributeValidator.new('String', ["short", "standard", "legal_hold"])
      unless validator.valid?(retention_policy)
        fail ArgumentError, "invalid value for \"retention_policy\", must be one of #{validator.allowable_values}."
      end
      @retention_policy = retention_policy
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["active", "expired", "tombstoned"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] created_by_type Object to be assigned
    def created_by_type=(created_by_type)
      validator = EnumAttributeValidator.new('String', ["system", "user", "service"])
      unless validator.valid?(created_by_type)
        fail ArgumentError, "invalid value for \"created_by_type\", must be one of #{validator.allowable_values}."
      end
      @created_by_type = created_by_type
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          project_id == o.project_id &&
          evidence_ref == o.evidence_ref &&
          media_type == o.media_type &&
          source_kind == o.source_kind &&
          source_uri == o.source_uri &&
          content_sha256 == o.content_sha256 &&
          content_length == o.content_length &&
          mime_type == o.mime_type &&
          language == o.language &&
          retention_policy == o.retention_policy &&
          expires_at_utc == o.expires_at_utc &&
          status == o.status &&
          created_by_type == o.created_by_type &&
          created_by_id == o.created_by_id &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, project_id, evidence_ref, media_type, source_kind, source_uri, content_sha256, content_length, mime_type, language, retention_policy, expires_at_utc, status, created_by_type, created_by_id, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
