=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class LedgerIngestRun < ApiModelBase
    attr_accessor :id

    attr_accessor :project_id

    attr_accessor :mode

    # Present when mode=single_event.
    attr_accessor :source_event_key

    attr_accessor :from_ts

    attr_accessor :to_ts

    attr_accessor :filter

    attr_accessor :idempotency_key

    attr_accessor :status

    attr_accessor :run_id

    attr_accessor :trace_id

    attr_accessor :policy_version_id

    attr_accessor :stats

    attr_accessor :evidence_refs

    attr_accessor :created_at

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'project_id' => :'project_id',
        :'mode' => :'mode',
        :'source_event_key' => :'source_event_key',
        :'from_ts' => :'from_ts',
        :'to_ts' => :'to_ts',
        :'filter' => :'filter',
        :'idempotency_key' => :'idempotency_key',
        :'status' => :'status',
        :'run_id' => :'run_id',
        :'trace_id' => :'trace_id',
        :'policy_version_id' => :'policy_version_id',
        :'stats' => :'stats',
        :'evidence_refs' => :'evidence_refs',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'project_id' => :'String',
        :'mode' => :'String',
        :'source_event_key' => :'String',
        :'from_ts' => :'Time',
        :'to_ts' => :'Time',
        :'filter' => :'Hash<String, Object>',
        :'idempotency_key' => :'String',
        :'status' => :'String',
        :'run_id' => :'String',
        :'trace_id' => :'String',
        :'policy_version_id' => :'String',
        :'stats' => :'Hash<String, Object>',
        :'evidence_refs' => :'Array<String>',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'source_event_key',
        :'from_ts',
        :'to_ts',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::LedgerIngestRun` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::LedgerIngestRun`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      else
        self.project_id = nil
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      else
        self.mode = nil
      end

      if attributes.key?(:'source_event_key')
        self.source_event_key = attributes[:'source_event_key']
      end

      if attributes.key?(:'from_ts')
        self.from_ts = attributes[:'from_ts']
      end

      if attributes.key?(:'to_ts')
        self.to_ts = attributes[:'to_ts']
      end

      if attributes.key?(:'filter')
        if (value = attributes[:'filter']).is_a?(Hash)
          self.filter = value
        end
      else
        self.filter = nil
      end

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      else
        self.idempotency_key = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'run_id')
        self.run_id = attributes[:'run_id']
      else
        self.run_id = nil
      end

      if attributes.key?(:'trace_id')
        self.trace_id = attributes[:'trace_id']
      else
        self.trace_id = nil
      end

      if attributes.key?(:'policy_version_id')
        self.policy_version_id = attributes[:'policy_version_id']
      else
        self.policy_version_id = nil
      end

      if attributes.key?(:'stats')
        if (value = attributes[:'stats']).is_a?(Hash)
          self.stats = value
        end
      else
        self.stats = nil
      end

      if attributes.key?(:'evidence_refs')
        if (value = attributes[:'evidence_refs']).is_a?(Array)
          self.evidence_refs = value
        end
      else
        self.evidence_refs = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @project_id.nil?
        invalid_properties.push('invalid value for "project_id", project_id cannot be nil.')
      end

      if @mode.nil?
        invalid_properties.push('invalid value for "mode", mode cannot be nil.')
      end

      if @filter.nil?
        invalid_properties.push('invalid value for "filter", filter cannot be nil.')
      end

      if @idempotency_key.nil?
        invalid_properties.push('invalid value for "idempotency_key", idempotency_key cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @run_id.nil?
        invalid_properties.push('invalid value for "run_id", run_id cannot be nil.')
      end

      if @trace_id.nil?
        invalid_properties.push('invalid value for "trace_id", trace_id cannot be nil.')
      end

      if @policy_version_id.nil?
        invalid_properties.push('invalid value for "policy_version_id", policy_version_id cannot be nil.')
      end

      if @stats.nil?
        invalid_properties.push('invalid value for "stats", stats cannot be nil.')
      end

      if @evidence_refs.nil?
        invalid_properties.push('invalid value for "evidence_refs", evidence_refs cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @project_id.nil?
      return false if @mode.nil?
      mode_validator = EnumAttributeValidator.new('String', ["single_event", "range"])
      return false unless mode_validator.valid?(@mode)
      return false if @filter.nil?
      return false if @idempotency_key.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["accepted", "running", "succeeded", "failed_recorded"])
      return false unless status_validator.valid?(@status)
      return false if @run_id.nil?
      return false if @trace_id.nil?
      return false if @policy_version_id.nil?
      return false if @stats.nil?
      return false if @evidence_refs.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] project_id Value to be assigned
    def project_id=(project_id)
      if project_id.nil?
        fail ArgumentError, 'project_id cannot be nil'
      end

      @project_id = project_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] mode Object to be assigned
    def mode=(mode)
      validator = EnumAttributeValidator.new('String', ["single_event", "range"])
      unless validator.valid?(mode)
        fail ArgumentError, "invalid value for \"mode\", must be one of #{validator.allowable_values}."
      end
      @mode = mode
    end

    # Custom attribute writer method with validation
    # @param [Object] filter Value to be assigned
    def filter=(filter)
      if filter.nil?
        fail ArgumentError, 'filter cannot be nil'
      end

      @filter = filter
    end

    # Custom attribute writer method with validation
    # @param [Object] idempotency_key Value to be assigned
    def idempotency_key=(idempotency_key)
      if idempotency_key.nil?
        fail ArgumentError, 'idempotency_key cannot be nil'
      end

      @idempotency_key = idempotency_key
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["accepted", "running", "succeeded", "failed_recorded"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] run_id Value to be assigned
    def run_id=(run_id)
      if run_id.nil?
        fail ArgumentError, 'run_id cannot be nil'
      end

      @run_id = run_id
    end

    # Custom attribute writer method with validation
    # @param [Object] trace_id Value to be assigned
    def trace_id=(trace_id)
      if trace_id.nil?
        fail ArgumentError, 'trace_id cannot be nil'
      end

      @trace_id = trace_id
    end

    # Custom attribute writer method with validation
    # @param [Object] policy_version_id Value to be assigned
    def policy_version_id=(policy_version_id)
      if policy_version_id.nil?
        fail ArgumentError, 'policy_version_id cannot be nil'
      end

      @policy_version_id = policy_version_id
    end

    # Custom attribute writer method with validation
    # @param [Object] stats Value to be assigned
    def stats=(stats)
      if stats.nil?
        fail ArgumentError, 'stats cannot be nil'
      end

      @stats = stats
    end

    # Custom attribute writer method with validation
    # @param [Object] evidence_refs Value to be assigned
    def evidence_refs=(evidence_refs)
      if evidence_refs.nil?
        fail ArgumentError, 'evidence_refs cannot be nil'
      end

      @evidence_refs = evidence_refs
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          project_id == o.project_id &&
          mode == o.mode &&
          source_event_key == o.source_event_key &&
          from_ts == o.from_ts &&
          to_ts == o.to_ts &&
          filter == o.filter &&
          idempotency_key == o.idempotency_key &&
          status == o.status &&
          run_id == o.run_id &&
          trace_id == o.trace_id &&
          policy_version_id == o.policy_version_id &&
          stats == o.stats &&
          evidence_refs == o.evidence_refs &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, project_id, mode, source_event_key, from_ts, to_ts, filter, idempotency_key, status, run_id, trace_id, policy_version_id, stats, evidence_refs, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
