=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class PolicyEvaluateRequest < ApiModelBase
    attr_accessor :run_id

    attr_accessor :policy_version_str

    attr_accessor :pipeline_version

    attr_accessor :inputs_evidence_asset_id

    attr_accessor :reason_evidence_asset_id

    attr_accessor :obligations_evidence_asset_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'run_id' => :'run_id',
        :'policy_version_str' => :'policy_version_str',
        :'pipeline_version' => :'pipeline_version',
        :'inputs_evidence_asset_id' => :'inputs_evidence_asset_id',
        :'reason_evidence_asset_id' => :'reason_evidence_asset_id',
        :'obligations_evidence_asset_id' => :'obligations_evidence_asset_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'run_id' => :'String',
        :'policy_version_str' => :'String',
        :'pipeline_version' => :'String',
        :'inputs_evidence_asset_id' => :'Integer',
        :'reason_evidence_asset_id' => :'Integer',
        :'obligations_evidence_asset_id' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PolicyEvaluateRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PolicyEvaluateRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'run_id')
        self.run_id = attributes[:'run_id']
      else
        self.run_id = nil
      end

      if attributes.key?(:'policy_version_str')
        self.policy_version_str = attributes[:'policy_version_str']
      else
        self.policy_version_str = nil
      end

      if attributes.key?(:'pipeline_version')
        self.pipeline_version = attributes[:'pipeline_version']
      else
        self.pipeline_version = nil
      end

      if attributes.key?(:'inputs_evidence_asset_id')
        self.inputs_evidence_asset_id = attributes[:'inputs_evidence_asset_id']
      else
        self.inputs_evidence_asset_id = nil
      end

      if attributes.key?(:'reason_evidence_asset_id')
        self.reason_evidence_asset_id = attributes[:'reason_evidence_asset_id']
      else
        self.reason_evidence_asset_id = nil
      end

      if attributes.key?(:'obligations_evidence_asset_id')
        self.obligations_evidence_asset_id = attributes[:'obligations_evidence_asset_id']
      else
        self.obligations_evidence_asset_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @run_id.nil?
        invalid_properties.push('invalid value for "run_id", run_id cannot be nil.')
      end

      if @policy_version_str.nil?
        invalid_properties.push('invalid value for "policy_version_str", policy_version_str cannot be nil.')
      end

      if @pipeline_version.nil?
        invalid_properties.push('invalid value for "pipeline_version", pipeline_version cannot be nil.')
      end

      if @inputs_evidence_asset_id.nil?
        invalid_properties.push('invalid value for "inputs_evidence_asset_id", inputs_evidence_asset_id cannot be nil.')
      end

      if @reason_evidence_asset_id.nil?
        invalid_properties.push('invalid value for "reason_evidence_asset_id", reason_evidence_asset_id cannot be nil.')
      end

      if @obligations_evidence_asset_id.nil?
        invalid_properties.push('invalid value for "obligations_evidence_asset_id", obligations_evidence_asset_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @run_id.nil?
      return false if @policy_version_str.nil?
      return false if @pipeline_version.nil?
      return false if @inputs_evidence_asset_id.nil?
      return false if @reason_evidence_asset_id.nil?
      return false if @obligations_evidence_asset_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] run_id Value to be assigned
    def run_id=(run_id)
      if run_id.nil?
        fail ArgumentError, 'run_id cannot be nil'
      end

      @run_id = run_id
    end

    # Custom attribute writer method with validation
    # @param [Object] policy_version_str Value to be assigned
    def policy_version_str=(policy_version_str)
      if policy_version_str.nil?
        fail ArgumentError, 'policy_version_str cannot be nil'
      end

      @policy_version_str = policy_version_str
    end

    # Custom attribute writer method with validation
    # @param [Object] pipeline_version Value to be assigned
    def pipeline_version=(pipeline_version)
      if pipeline_version.nil?
        fail ArgumentError, 'pipeline_version cannot be nil'
      end

      @pipeline_version = pipeline_version
    end

    # Custom attribute writer method with validation
    # @param [Object] inputs_evidence_asset_id Value to be assigned
    def inputs_evidence_asset_id=(inputs_evidence_asset_id)
      if inputs_evidence_asset_id.nil?
        fail ArgumentError, 'inputs_evidence_asset_id cannot be nil'
      end

      @inputs_evidence_asset_id = inputs_evidence_asset_id
    end

    # Custom attribute writer method with validation
    # @param [Object] reason_evidence_asset_id Value to be assigned
    def reason_evidence_asset_id=(reason_evidence_asset_id)
      if reason_evidence_asset_id.nil?
        fail ArgumentError, 'reason_evidence_asset_id cannot be nil'
      end

      @reason_evidence_asset_id = reason_evidence_asset_id
    end

    # Custom attribute writer method with validation
    # @param [Object] obligations_evidence_asset_id Value to be assigned
    def obligations_evidence_asset_id=(obligations_evidence_asset_id)
      if obligations_evidence_asset_id.nil?
        fail ArgumentError, 'obligations_evidence_asset_id cannot be nil'
      end

      @obligations_evidence_asset_id = obligations_evidence_asset_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          run_id == o.run_id &&
          policy_version_str == o.policy_version_str &&
          pipeline_version == o.pipeline_version &&
          inputs_evidence_asset_id == o.inputs_evidence_asset_id &&
          reason_evidence_asset_id == o.reason_evidence_asset_id &&
          obligations_evidence_asset_id == o.obligations_evidence_asset_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [run_id, policy_version_str, pipeline_version, inputs_evidence_asset_id, reason_evidence_asset_id, obligations_evidence_asset_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
