BEGIN;

-- tables
REVOKE ALL ON TABLE run_schedules FROM PUBLIC;
REVOKE ALL ON TABLE scheduled_runs FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE run_schedules TO ak;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE scheduled_runs TO ak;

-- sequences
GRANT USAGE, SELECT ON SEQUENCE run_schedules_id_seq TO ak;
GRANT USAGE, SELECT ON SEQUENCE scheduled_runs_id_seq TO ak;

-- functions
REVOKE ALL ON FUNCTION runsched_tick_enqueue_v19(VARCHAR, TIMESTAMPTZ, INTEGER, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION runsched_dispatch_create_run_v19(VARCHAR, INTEGER, TIMESTAMPTZ) FROM PUBLIC;
REVOKE ALL ON FUNCTION runsched_mark_skipped_v19(VARCHAR, BIGINT, TEXT, TEXT, BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION runsched_mark_error_v19(VARCHAR, BIGINT, TEXT, BIGINT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION runsched_tick_enqueue_v19(VARCHAR, TIMESTAMPTZ, INTEGER, JSONB) TO ak;
GRANT EXECUTE ON FUNCTION runsched_dispatch_create_run_v19(VARCHAR, INTEGER, TIMESTAMPTZ) TO ak;
GRANT EXECUTE ON FUNCTION runsched_mark_skipped_v19(VARCHAR, BIGINT, TEXT, TEXT, BIGINT) TO ak;
GRANT EXECUTE ON FUNCTION runsched_mark_error_v19(VARCHAR, BIGINT, TEXT, BIGINT) TO ak;

COMMIT;