BEGIN;

REVOKE ALL ON TABLE budget_reservations_v19 FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE budget_reservations_v19 TO ak;

REVOKE ALL ON FUNCTION runsched_budget_gate_check_v19(TEXT, TIMESTAMPTZ, BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION runsched_budget_reserve_v19(TEXT, BIGINT, TEXT, BIGINT, TEXT, BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION runsched_budget_consume_v19(TEXT, BIGINT, UUID, TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION runsched_budget_gate_check_v19(TEXT, TIMESTAMPTZ, BIGINT) TO ak;
GRANT EXECUTE ON FUNCTION runsched_budget_reserve_v19(TEXT, BIGINT, TEXT, BIGINT, TEXT, BIGINT) TO ak;
GRANT EXECUTE ON FUNCTION runsched_budget_consume_v19(TEXT, BIGINT, UUID, TEXT) TO ak;

COMMIT;