package worker

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"

	run "example.com/pisag_go/run"
)

type StubLLMAdapter struct{}

func (a *StubLLMAdapter) ExecuteLLM(ctx context.Context, in run.LLMExecutionInput) (run.LLMExecutionOutput, error) {
	_ = ctx

	if in.Task.ID <= 0 {
		return run.LLMExecutionOutput{}, fmt.Errorf("stub llm adapter: task id is required")
	}
	if in.TaskKind == "" {
		return run.LLMExecutionOutput{}, fmt.Errorf("stub llm adapter: task_kind is required")
	}

	engineKind := run.EngineKindGemma3
	if primary, ok := in.Selection.PrimaryChoice(run.EngineCapabilityLLM); ok {
		engineKind = primary.Kind
	}

	provider := providerFromEngineKind(engineKind)
	outputText := buildStubLLMText(in.TaskKind, in.Context)
	outputJSON := buildStubLLMJSON(in.TaskKind, outputText)
	rationale := fmt.Sprintf("stub llm executed with engine=%s task_kind=%s", engineKind, in.TaskKind)
	summary := fmt.Sprintf("llm completed: engine=%s task_kind=%s", engineKind, in.TaskKind)
	outputHash := sha256HexLLM(outputText + "|" + string(in.TaskKind))

	var costEstimate *float64
	switch provider {
	case run.EngineProviderOpenAI, run.EngineProviderGoogle, run.EngineProviderAnthropic:
		costEstimate = floatPtrLLM(0.0015)
	default:
		costEstimate = nil
	}

	return run.LLMExecutionOutput{
		PayloadEvidenceAssetID:    stubLLMEvidenceIDFromTask(in.Task.ID, 4001),
		ConfidenceEvidenceAssetID: nil,
		GeneratedOutputs: []run.MultimodalGeneratedOutput{
			{
				EvidenceID: stubLLMEvidenceIDFromTask(in.Task.ID, 4002),
				OutputRole: run.MultimodalOutputRoleLLMText,
				Seq:        1,
			},
			{
				EvidenceID: stubLLMEvidenceIDFromTask(in.Task.ID, 4003),
				OutputRole: run.MultimodalOutputRoleLLMJSON,
				Seq:        2,
			},
		},
		OutputHash:      outputHash,
		SummaryText:     summary,
		ConfidenceScore: floatPtrLLM(0.86),
		ReasonCode:      "llm_ok",
		ReviewRequired:  false,
		EngineKind:      engineKind,
		EngineVersion:   "v1",
		Metadata: map[string]any{
			"adapter":    "stub_llm",
			"task_type":  string(in.Task.TaskType),
			"task_kind":  string(in.TaskKind),
			"project_id": in.Task.ProjectID,
			"selection":  llmSelectionKinds(in.Selection),
		},
		OutputText:     outputText,
		OutputJSON:     outputJSON,
		RationaleText:  rationale,
		PromptVersion:  "v1",
		TokenUsageJSON: map[string]any{"input_tokens": 100, "output_tokens": 60, "total_tokens": 160},
		CostEstimate:   costEstimate,
	}, nil
}

func llmSelectionKinds(sel run.EngineSelection) []string {
	out := make([]string, 0, len(sel.LLM))
	for _, ch := range sel.LLM {
		out = append(out, string(ch.Kind))
	}
	return out
}

func providerFromEngineKind(kind run.EngineKind) run.EngineProvider {
	switch kind {
	case run.EngineKindGPT5:
		return run.EngineProviderOpenAI
	case run.EngineKindGeminiFlash:
		return run.EngineProviderGoogle
	case run.EngineKindClaudeHaiku45:
		return run.EngineProviderAnthropic
	case run.EngineKindGemma3, run.EngineKindMistralSmall:
		return run.EngineProviderOpenSource
	default:
		return run.EngineProviderLocal
	}
}

func buildStubLLMText(taskKind run.LLMTaskKind, ctx map[string]any) string {
	switch taskKind {
	case run.LLMTaskKindGenerateCopy:
		return "This is a generated product copy stub."
	case run.LLMTaskKindPolicyCheck:
		return "Policy check completed. No critical issue detected in stub mode."
	case run.LLMTaskKindAttributeExplain:
		return "This is an attribute explanation generated by the stub adapter."
	case run.LLMTaskKindSummarize:
		fallthrough
	default:
		return fmt.Sprintf("Summary stub generated. Context keys=%d", len(ctx))
	}
}

func buildStubLLMJSON(taskKind run.LLMTaskKind, outputText string) map[string]any {
	return map[string]any{
		"task_kind": string(taskKind),
		"output":    outputText,
	}
}

func stubLLMEvidenceIDFromTask(taskID int64, offset int64) int64 {
	return taskID*100000 + offset
}

func sha256HexLLM(s string) string {
	sum := sha256.Sum256([]byte(s))
	return hex.EncodeToString(sum[:])
}

func floatPtrLLM(v float64) *float64 {
	return &v
}