# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class DecisionProposeRequest(BaseModel):
    """
    DecisionProposeRequest
    """ # noqa: E501
    run_id: StrictStr
    policy_evaluation_id: StrictInt
    subject_type: StrictStr
    subject_id: StrictStr
    decision_scope: StrictStr
    policy_version_str: StrictStr
    pipeline_version: StrictStr
    input_hash: StrictStr
    inputs_evidence_asset_id: StrictInt
    obligations_evidence_asset_id: StrictInt
    __properties: ClassVar[List[str]] = ["run_id", "policy_evaluation_id", "subject_type", "subject_id", "decision_scope", "policy_version_str", "pipeline_version", "input_hash", "inputs_evidence_asset_id", "obligations_evidence_asset_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DecisionProposeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DecisionProposeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "run_id": obj.get("run_id"),
            "policy_evaluation_id": obj.get("policy_evaluation_id"),
            "subject_type": obj.get("subject_type"),
            "subject_id": obj.get("subject_id"),
            "decision_scope": obj.get("decision_scope"),
            "policy_version_str": obj.get("policy_version_str"),
            "pipeline_version": obj.get("pipeline_version"),
            "input_hash": obj.get("input_hash"),
            "inputs_evidence_asset_id": obj.get("inputs_evidence_asset_id"),
            "obligations_evidence_asset_id": obj.get("obligations_evidence_asset_id")
        })
        return _obj


