# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DecisionApplyRequest(BaseModel):
    """
    DecisionApplyRequest
    """ # noqa: E501
    run_id: StrictStr
    action_type: Optional[StrictStr] = None
    action_scope: Optional[StrictStr] = None
    target_evidence_asset_id: StrictInt
    plan_evidence_asset_id: StrictInt
    budget_currency: Optional[StrictStr] = None
    budget_estimate_amount: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["run_id", "action_type", "action_scope", "target_evidence_asset_id", "plan_evidence_asset_id", "budget_currency", "budget_estimate_amount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DecisionApplyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DecisionApplyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "run_id": obj.get("run_id"),
            "action_type": obj.get("action_type"),
            "action_scope": obj.get("action_scope"),
            "target_evidence_asset_id": obj.get("target_evidence_asset_id"),
            "plan_evidence_asset_id": obj.get("plan_evidence_asset_id"),
            "budget_currency": obj.get("budget_currency"),
            "budget_estimate_amount": obj.get("budget_estimate_amount")
        })
        return _obj


