# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class EvidenceAsset(BaseModel):
    """
    EvidenceAsset
    """ # noqa: E501
    id: StrictInt
    project_id: StrictStr
    evidence_ref: UUID
    media_type: StrictStr
    source_kind: StrictStr
    source_uri: Optional[StrictStr] = None
    content_sha256: Annotated[str, Field(min_length=64, strict=True, max_length=64)]
    content_length: StrictInt
    mime_type: StrictStr
    language: Optional[StrictStr] = None
    retention_policy: StrictStr
    expires_at_utc: Optional[datetime] = None
    status: StrictStr
    created_by_type: StrictStr
    created_by_id: Optional[StrictStr] = None
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["id", "project_id", "evidence_ref", "media_type", "source_kind", "source_uri", "content_sha256", "content_length", "mime_type", "language", "retention_policy", "expires_at_utc", "status", "created_by_type", "created_by_id", "created_at", "updated_at"]

    @field_validator('media_type')
    def media_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['text', 'image', 'audio', 'video', 'binary']):
            raise ValueError("must be one of enum values ('text', 'image', 'audio', 'video', 'binary')")
        return value

    @field_validator('source_kind')
    def source_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pisag_fetch', 'upload', 'webhook', 'generated', 'import']):
            raise ValueError("must be one of enum values ('pisag_fetch', 'upload', 'webhook', 'generated', 'import')")
        return value

    @field_validator('retention_policy')
    def retention_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['short', 'standard', 'legal_hold']):
            raise ValueError("must be one of enum values ('short', 'standard', 'legal_hold')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'expired', 'tombstoned']):
            raise ValueError("must be one of enum values ('active', 'expired', 'tombstoned')")
        return value

    @field_validator('created_by_type')
    def created_by_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['system', 'user', 'service']):
            raise ValueError("must be one of enum values ('system', 'user', 'service')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EvidenceAsset from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if source_uri (nullable) is None
        # and model_fields_set contains the field
        if self.source_uri is None and "source_uri" in self.model_fields_set:
            _dict['source_uri'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if expires_at_utc (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at_utc is None and "expires_at_utc" in self.model_fields_set:
            _dict['expires_at_utc'] = None

        # set to None if created_by_id (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_id is None and "created_by_id" in self.model_fields_set:
            _dict['created_by_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EvidenceAsset from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project_id": obj.get("project_id"),
            "evidence_ref": obj.get("evidence_ref"),
            "media_type": obj.get("media_type"),
            "source_kind": obj.get("source_kind"),
            "source_uri": obj.get("source_uri"),
            "content_sha256": obj.get("content_sha256"),
            "content_length": obj.get("content_length"),
            "mime_type": obj.get("mime_type"),
            "language": obj.get("language"),
            "retention_policy": obj.get("retention_policy"),
            "expires_at_utc": obj.get("expires_at_utc"),
            "status": obj.get("status"),
            "created_by_type": obj.get("created_by_type"),
            "created_by_id": obj.get("created_by_id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


