# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class LedgerIngestRun(BaseModel):
    """
    LedgerIngestRun
    """ # noqa: E501
    id: UUID
    project_id: StrictStr
    mode: StrictStr
    source_event_key: Optional[StrictStr] = Field(default=None, description="Present when mode=single_event.")
    from_ts: Optional[datetime] = None
    to_ts: Optional[datetime] = None
    filter: Dict[str, Any]
    idempotency_key: StrictStr
    status: StrictStr
    run_id: StrictStr
    trace_id: StrictStr
    policy_version_id: StrictStr
    stats: Dict[str, Any]
    evidence_refs: List[UUID]
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["id", "project_id", "mode", "source_event_key", "from_ts", "to_ts", "filter", "idempotency_key", "status", "run_id", "trace_id", "policy_version_id", "stats", "evidence_refs", "created_at", "updated_at"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['single_event', 'range']):
            raise ValueError("must be one of enum values ('single_event', 'range')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['accepted', 'running', 'succeeded', 'failed_recorded']):
            raise ValueError("must be one of enum values ('accepted', 'running', 'succeeded', 'failed_recorded')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LedgerIngestRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if source_event_key (nullable) is None
        # and model_fields_set contains the field
        if self.source_event_key is None and "source_event_key" in self.model_fields_set:
            _dict['source_event_key'] = None

        # set to None if from_ts (nullable) is None
        # and model_fields_set contains the field
        if self.from_ts is None and "from_ts" in self.model_fields_set:
            _dict['from_ts'] = None

        # set to None if to_ts (nullable) is None
        # and model_fields_set contains the field
        if self.to_ts is None and "to_ts" in self.model_fields_set:
            _dict['to_ts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LedgerIngestRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project_id": obj.get("project_id"),
            "mode": obj.get("mode"),
            "source_event_key": obj.get("source_event_key"),
            "from_ts": obj.get("from_ts"),
            "to_ts": obj.get("to_ts"),
            "filter": obj.get("filter"),
            "idempotency_key": obj.get("idempotency_key"),
            "status": obj.get("status"),
            "run_id": obj.get("run_id"),
            "trace_id": obj.get("trace_id"),
            "policy_version_id": obj.get("policy_version_id"),
            "stats": obj.get("stats"),
            "evidence_refs": obj.get("evidence_refs"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


