=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DecisionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DecisionsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DecisionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DecisionsApi' do
    it 'should create an instance of DecisionsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DecisionsApi)
    end
  end

  # unit tests for post_decision_apply
  # Apply a decision (enqueue action) with gate
  # v23 gate - if decision is not approved, actions&#x3D;[] and blocked_reason is returned.
  # @param project_id 
  # @param decision_id 
  # @param decision_apply_request 
  # @param [Hash] opts the optional parameters
  # @return [DecisionApplyResponse]
  describe 'post_decision_apply test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_decision_approve
  # Approve a decision
  # @param project_id 
  # @param decision_id 
  # @param [Hash] opts the optional parameters
  # @option opts [DecisionApproveRequest] :decision_approve_request 
  # @return [DecisionApproveResponse]
  describe 'post_decision_approve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_decision_propose
  # Decision propose (create ledger)
  # @param project_id 
  # @param decision_propose_request 
  # @param [Hash] opts the optional parameters
  # @return [DecisionProposeResponse]
  describe 'post_decision_propose test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
