=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::EvidenceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EvidenceApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::EvidenceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EvidenceApi' do
    it 'should create an instance of EvidenceApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::EvidenceApi)
    end
  end

  # unit tests for get_evidence_asset_by_ref
  # Get evidence asset by evidence_ref
  # Read-only. Returns evidence_assets row by (project_id, evidence_ref).
  # @param project_id 
  # @param evidence_ref 
  # @param [Hash] opts the optional parameters
  # @return [EvidenceAsset]
  describe 'get_evidence_asset_by_ref test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
