=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::HealthApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HealthApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::HealthApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HealthApi' do
    it 'should create an instance of HealthApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::HealthApi)
    end
  end

  # unit tests for get_health
  # Health check
  # @param [Hash] opts the optional parameters
  # @return [HealthResponse]
  describe 'get_health test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
