=begin
#AtlasKernel Platform API

#Single Source of Contract (v24). Implementations must conform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::LedgerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LedgerApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::LedgerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LedgerApi' do
    it 'should create an instance of LedgerApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::LedgerApi)
    end
  end

  # unit tests for get_ledger_ingest_run
  # Get ledger ingest run
  # Read-only. Returns a single ingest run by id (v14.1+).
  # @param project_id 
  # @param ingest_run_id 
  # @param [Hash] opts the optional parameters
  # @return [LedgerIngestRun]
  describe 'get_ledger_ingest_run test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_ledger_ingest_runs
  # List ledger ingest runs
  # Read-only. Returns run-based UTL→Ledger ingest runs (v14.1+).
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status Filter by ingest run status.
  # @option opts [Time] :from RFC3339 lower bound for created_at (inclusive).
  # @option opts [Time] :to RFC3339 upper bound for created_at (exclusive).
  # @option opts [Integer] :limit Max items.
  # @return [LedgerIngestRunListResponse]
  describe 'list_ledger_ingest_runs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
