# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.decision_apply_request import DecisionApplyRequest

class TestDecisionApplyRequest(unittest.TestCase):
    """DecisionApplyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecisionApplyRequest:
        """Test DecisionApplyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DecisionApplyRequest`
        """
        model = DecisionApplyRequest()
        if include_optional:
            return DecisionApplyRequest(
                run_id = '',
                action_type = 'publish_http',
                action_scope = 'managed',
                target_evidence_asset_id = 45,
                plan_evidence_asset_id = 46,
                budget_currency = 'usd_micros',
                budget_estimate_amount = 1000
            )
        else:
            return DecisionApplyRequest(
                run_id = '',
                target_evidence_asset_id = 45,
                plan_evidence_asset_id = 46,
        )
        """

    def testDecisionApplyRequest(self):
        """Test DecisionApplyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
