# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.policy_evaluate_response import PolicyEvaluateResponse

class TestPolicyEvaluateResponse(unittest.TestCase):
    """PolicyEvaluateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyEvaluateResponse:
        """Test PolicyEvaluateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyEvaluateResponse`
        """
        model = PolicyEvaluateResponse()
        if include_optional:
            return PolicyEvaluateResponse(
                input_hash = 'f475fdf47ee7a1b7d5a381cc56b4dd5c7ad8f25c0f1ae8f904ae9b1328e312cc',
                policy_evaluation_id = 11,
                result = 'allow',
                trace_id = 'trc_v24_ok'
            )
        else:
            return PolicyEvaluateResponse(
                input_hash = 'f475fdf47ee7a1b7d5a381cc56b4dd5c7ad8f25c0f1ae8f904ae9b1328e312cc',
                policy_evaluation_id = 11,
                result = 'allow',
                trace_id = 'trc_v24_ok',
        )
        """

    def testPolicyEvaluateResponse(self):
        """Test PolicyEvaluateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
