# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.decision_apply_response import DecisionApplyResponse

class TestDecisionApplyResponse(unittest.TestCase):
    """DecisionApplyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecisionApplyResponse:
        """Test DecisionApplyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DecisionApplyResponse`
        """
        model = DecisionApplyResponse()
        if include_optional:
            return DecisionApplyResponse(
                trace_id = '',
                decision_id = 56,
                decision_status = '',
                decision_kind = '',
                blocked_reason = '',
                actions = [
                    openapi_client.models.action_ref.ActionRef(
                        action_id = 56, 
                        status = 'queued', )
                    ]
            )
        else:
            return DecisionApplyResponse(
                trace_id = '',
                decision_id = 56,
                actions = [
                    openapi_client.models.action_ref.ActionRef(
                        action_id = 56, 
                        status = 'queued', )
                    ],
        )
        """

    def testDecisionApplyResponse(self):
        """Test DecisionApplyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
