# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.action_ref import ActionRef

class TestActionRef(unittest.TestCase):
    """ActionRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionRef:
        """Test ActionRef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionRef`
        """
        model = ActionRef()
        if include_optional:
            return ActionRef(
                action_id = 56,
                status = 'queued'
            )
        else:
            return ActionRef(
                action_id = 56,
                status = 'queued',
        )
        """

    def testActionRef(self):
        """Test ActionRef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
