# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.decisions_api import DecisionsApi


class TestDecisionsApi(unittest.TestCase):
    """DecisionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DecisionsApi()

    def tearDown(self) -> None:
        pass

    def test_post_decision_apply(self) -> None:
        """Test case for post_decision_apply

        Apply a decision (enqueue action) with gate
        """
        pass

    def test_post_decision_approve(self) -> None:
        """Test case for post_decision_approve

        Approve a decision
        """
        pass

    def test_post_decision_propose(self) -> None:
        """Test case for post_decision_propose

        Decision propose (create ledger)
        """
        pass


if __name__ == '__main__':
    unittest.main()
