# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ledger_ingest_run import LedgerIngestRun

class TestLedgerIngestRun(unittest.TestCase):
    """LedgerIngestRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LedgerIngestRun:
        """Test LedgerIngestRun
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LedgerIngestRun`
        """
        model = LedgerIngestRun()
        if include_optional:
            return LedgerIngestRun(
                id = '',
                project_id = '',
                mode = 'single_event',
                source_event_key = '',
                from_ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                to_ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                filter = { },
                idempotency_key = '',
                status = 'accepted',
                run_id = '',
                trace_id = '',
                policy_version_id = '',
                stats = { },
                evidence_refs = [
                    ''
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return LedgerIngestRun(
                id = '',
                project_id = '',
                mode = 'single_event',
                filter = { },
                idempotency_key = '',
                status = 'accepted',
                run_id = '',
                trace_id = '',
                policy_version_id = '',
                stats = { },
                evidence_refs = [
                    ''
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testLedgerIngestRun(self):
        """Test LedgerIngestRun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
