# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.evidence_asset import EvidenceAsset

class TestEvidenceAsset(unittest.TestCase):
    """EvidenceAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvidenceAsset:
        """Test EvidenceAsset
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvidenceAsset`
        """
        model = EvidenceAsset()
        if include_optional:
            return EvidenceAsset(
                id = 56,
                project_id = '',
                evidence_ref = '',
                media_type = 'text',
                source_kind = 'pisag_fetch',
                source_uri = '',
                content_sha256 = '0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263',
                content_length = 56,
                mime_type = '',
                language = '',
                retention_policy = 'short',
                expires_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'active',
                created_by_type = 'system',
                created_by_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return EvidenceAsset(
                id = 56,
                project_id = '',
                evidence_ref = '',
                media_type = 'text',
                source_kind = 'pisag_fetch',
                content_sha256 = '0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263',
                content_length = 56,
                mime_type = '',
                retention_policy = 'short',
                status = 'active',
                created_by_type = 'system',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testEvidenceAsset(self):
        """Test EvidenceAsset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
