# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.evidence_api import EvidenceApi


class TestEvidenceApi(unittest.TestCase):
    """EvidenceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EvidenceApi()

    def tearDown(self) -> None:
        pass

    def test_get_evidence_asset_by_ref(self) -> None:
        """Test case for get_evidence_asset_by_ref

        Get evidence asset by evidence_ref
        """
        pass


if __name__ == '__main__':
    unittest.main()
