# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ledger_api import LedgerApi


class TestLedgerApi(unittest.TestCase):
    """LedgerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LedgerApi()

    def tearDown(self) -> None:
        pass

    def test_get_ledger_ingest_run(self) -> None:
        """Test case for get_ledger_ingest_run

        Get ledger ingest run
        """
        pass

    def test_list_ledger_ingest_runs(self) -> None:
        """Test case for list_ledger_ingest_runs

        List ledger ingest runs
        """
        pass


if __name__ == '__main__':
    unittest.main()
