# coding: utf-8

"""
    AtlasKernel Platform API

    Single Source of Contract (v24). Implementations must conform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.policy_evaluate_request import PolicyEvaluateRequest

class TestPolicyEvaluateRequest(unittest.TestCase):
    """PolicyEvaluateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyEvaluateRequest:
        """Test PolicyEvaluateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyEvaluateRequest`
        """
        model = PolicyEvaluateRequest()
        if include_optional:
            return PolicyEvaluateRequest(
                run_id = '00000000-0000-0000-0000-000000000000',
                policy_version_str = 'v23',
                pipeline_version = 'v23',
                inputs_evidence_asset_id = 68,
                reason_evidence_asset_id = 69,
                obligations_evidence_asset_id = 44
            )
        else:
            return PolicyEvaluateRequest(
                run_id = '00000000-0000-0000-0000-000000000000',
                policy_version_str = 'v23',
                pipeline_version = 'v23',
                inputs_evidence_asset_id = 68,
                reason_evidence_asset_id = 69,
                obligations_evidence_asset_id = 44,
        )
        """

    def testPolicyEvaluateRequest(self):
        """Test PolicyEvaluateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
