/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DecisionApplyRequest,
  DecisionApplyResponse,
  DecisionApproveRequest,
  DecisionApproveResponse,
  DecisionProposeRequest,
  DecisionProposeResponse,
  ErrorResponse,
} from '../models/index';
import {
    DecisionApplyRequestFromJSON,
    DecisionApplyRequestToJSON,
    DecisionApplyResponseFromJSON,
    DecisionApplyResponseToJSON,
    DecisionApproveRequestFromJSON,
    DecisionApproveRequestToJSON,
    DecisionApproveResponseFromJSON,
    DecisionApproveResponseToJSON,
    DecisionProposeRequestFromJSON,
    DecisionProposeRequestToJSON,
    DecisionProposeResponseFromJSON,
    DecisionProposeResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface PostDecisionApplyRequest {
    projectId: string;
    decisionId: number;
    decisionApplyRequest: DecisionApplyRequest;
}

export interface PostDecisionApproveRequest {
    projectId: string;
    decisionId: number;
    decisionApproveRequest?: DecisionApproveRequest;
}

export interface PostDecisionProposeRequest {
    projectId: string;
    decisionProposeRequest: DecisionProposeRequest;
}

/**
 * 
 */
export class DecisionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for postDecisionApply without sending the request
     */
    async postDecisionApplyRequestOpts(requestParameters: PostDecisionApplyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling postDecisionApply().'
            );
        }

        if (requestParameters['decisionId'] == null) {
            throw new runtime.RequiredError(
                'decisionId',
                'Required parameter "decisionId" was null or undefined when calling postDecisionApply().'
            );
        }

        if (requestParameters['decisionApplyRequest'] == null) {
            throw new runtime.RequiredError(
                'decisionApplyRequest',
                'Required parameter "decisionApplyRequest" was null or undefined when calling postDecisionApply().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/projects/{project_id}/decisions/{decision_id}/apply`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"decision_id"}}`, encodeURIComponent(String(requestParameters['decisionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DecisionApplyRequestToJSON(requestParameters['decisionApplyRequest']),
        };
    }

    /**
     * v23 gate - if decision is not approved, actions=[] and blocked_reason is returned.
     * Apply a decision (enqueue action) with gate
     */
    async postDecisionApplyRaw(requestParameters: PostDecisionApplyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionApplyResponse>> {
        const requestOptions = await this.postDecisionApplyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionApplyResponseFromJSON(jsonValue));
    }

    /**
     * v23 gate - if decision is not approved, actions=[] and blocked_reason is returned.
     * Apply a decision (enqueue action) with gate
     */
    async postDecisionApply(requestParameters: PostDecisionApplyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionApplyResponse> {
        const response = await this.postDecisionApplyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postDecisionApprove without sending the request
     */
    async postDecisionApproveRequestOpts(requestParameters: PostDecisionApproveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling postDecisionApprove().'
            );
        }

        if (requestParameters['decisionId'] == null) {
            throw new runtime.RequiredError(
                'decisionId',
                'Required parameter "decisionId" was null or undefined when calling postDecisionApprove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/projects/{project_id}/decisions/{decision_id}/approve`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"decision_id"}}`, encodeURIComponent(String(requestParameters['decisionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DecisionApproveRequestToJSON(requestParameters['decisionApproveRequest']),
        };
    }

    /**
     * Approve a decision
     */
    async postDecisionApproveRaw(requestParameters: PostDecisionApproveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionApproveResponse>> {
        const requestOptions = await this.postDecisionApproveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionApproveResponseFromJSON(jsonValue));
    }

    /**
     * Approve a decision
     */
    async postDecisionApprove(requestParameters: PostDecisionApproveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionApproveResponse> {
        const response = await this.postDecisionApproveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postDecisionPropose without sending the request
     */
    async postDecisionProposeRequestOpts(requestParameters: PostDecisionProposeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling postDecisionPropose().'
            );
        }

        if (requestParameters['decisionProposeRequest'] == null) {
            throw new runtime.RequiredError(
                'decisionProposeRequest',
                'Required parameter "decisionProposeRequest" was null or undefined when calling postDecisionPropose().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/projects/{project_id}/decisions`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DecisionProposeRequestToJSON(requestParameters['decisionProposeRequest']),
        };
    }

    /**
     * Decision propose (create ledger)
     */
    async postDecisionProposeRaw(requestParameters: PostDecisionProposeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionProposeResponse>> {
        const requestOptions = await this.postDecisionProposeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionProposeResponseFromJSON(jsonValue));
    }

    /**
     * Decision propose (create ledger)
     */
    async postDecisionPropose(requestParameters: PostDecisionProposeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionProposeResponse> {
        const response = await this.postDecisionProposeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
