/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  EvidenceAsset,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    EvidenceAssetFromJSON,
    EvidenceAssetToJSON,
} from '../models/index';

export interface GetEvidenceAssetByRefRequest {
    projectId: string;
    evidenceRef: string;
}

/**
 * 
 */
export class EvidenceApi extends runtime.BaseAPI {

    /**
     * Creates request options for getEvidenceAssetByRef without sending the request
     */
    async getEvidenceAssetByRefRequestOpts(requestParameters: GetEvidenceAssetByRefRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getEvidenceAssetByRef().'
            );
        }

        if (requestParameters['evidenceRef'] == null) {
            throw new runtime.RequiredError(
                'evidenceRef',
                'Required parameter "evidenceRef" was null or undefined when calling getEvidenceAssetByRef().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/projects/{project_id}/evidence/{evidence_ref}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"evidence_ref"}}`, encodeURIComponent(String(requestParameters['evidenceRef'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read-only. Returns evidence_assets row by (project_id, evidence_ref).
     * Get evidence asset by evidence_ref
     */
    async getEvidenceAssetByRefRaw(requestParameters: GetEvidenceAssetByRefRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvidenceAsset>> {
        const requestOptions = await this.getEvidenceAssetByRefRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EvidenceAssetFromJSON(jsonValue));
    }

    /**
     * Read-only. Returns evidence_assets row by (project_id, evidence_ref).
     * Get evidence asset by evidence_ref
     */
    async getEvidenceAssetByRef(requestParameters: GetEvidenceAssetByRefRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvidenceAsset> {
        const response = await this.getEvidenceAssetByRefRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
