/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  LedgerIngestRun,
  LedgerIngestRunListResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LedgerIngestRunFromJSON,
    LedgerIngestRunToJSON,
    LedgerIngestRunListResponseFromJSON,
    LedgerIngestRunListResponseToJSON,
} from '../models/index';

export interface GetLedgerIngestRunRequest {
    projectId: string;
    ingestRunId: string;
}

export interface ListLedgerIngestRunsRequest {
    projectId: string;
    status?: ListLedgerIngestRunsStatusEnum;
    from?: Date;
    to?: Date;
    limit?: number;
}

/**
 * 
 */
export class LedgerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getLedgerIngestRun without sending the request
     */
    async getLedgerIngestRunRequestOpts(requestParameters: GetLedgerIngestRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getLedgerIngestRun().'
            );
        }

        if (requestParameters['ingestRunId'] == null) {
            throw new runtime.RequiredError(
                'ingestRunId',
                'Required parameter "ingestRunId" was null or undefined when calling getLedgerIngestRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/projects/{project_id}/ledger/ingest-runs/{ingest_run_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"ingest_run_id"}}`, encodeURIComponent(String(requestParameters['ingestRunId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read-only. Returns a single ingest run by id (v14.1+).
     * Get ledger ingest run
     */
    async getLedgerIngestRunRaw(requestParameters: GetLedgerIngestRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LedgerIngestRun>> {
        const requestOptions = await this.getLedgerIngestRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LedgerIngestRunFromJSON(jsonValue));
    }

    /**
     * Read-only. Returns a single ingest run by id (v14.1+).
     * Get ledger ingest run
     */
    async getLedgerIngestRun(requestParameters: GetLedgerIngestRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LedgerIngestRun> {
        const response = await this.getLedgerIngestRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listLedgerIngestRuns without sending the request
     */
    async listLedgerIngestRunsRequestOpts(requestParameters: ListLedgerIngestRunsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listLedgerIngestRuns().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/projects/{project_id}/ledger/ingest-runs`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read-only. Returns run-based UTL→Ledger ingest runs (v14.1+).
     * List ledger ingest runs
     */
    async listLedgerIngestRunsRaw(requestParameters: ListLedgerIngestRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LedgerIngestRunListResponse>> {
        const requestOptions = await this.listLedgerIngestRunsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LedgerIngestRunListResponseFromJSON(jsonValue));
    }

    /**
     * Read-only. Returns run-based UTL→Ledger ingest runs (v14.1+).
     * List ledger ingest runs
     */
    async listLedgerIngestRuns(requestParameters: ListLedgerIngestRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LedgerIngestRunListResponse> {
        const response = await this.listLedgerIngestRunsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListLedgerIngestRunsStatusEnum = {
    Accepted: 'accepted',
    Running: 'running',
    Succeeded: 'succeeded',
    FailedRecorded: 'failed_recorded'
} as const;
export type ListLedgerIngestRunsStatusEnum = typeof ListLedgerIngestRunsStatusEnum[keyof typeof ListLedgerIngestRunsStatusEnum];
