/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PolicyEvaluateRequest,
  PolicyEvaluateResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PolicyEvaluateRequestFromJSON,
    PolicyEvaluateRequestToJSON,
    PolicyEvaluateResponseFromJSON,
    PolicyEvaluateResponseToJSON,
} from '../models/index';

export interface PostPolicyEvaluateRequest {
    projectId: string;
    policyEvaluateRequest: PolicyEvaluateRequest;
}

/**
 * 
 */
export class PolicyApi extends runtime.BaseAPI {

    /**
     * Creates request options for postPolicyEvaluate without sending the request
     */
    async postPolicyEvaluateRequestOpts(requestParameters: PostPolicyEvaluateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling postPolicyEvaluate().'
            );
        }

        if (requestParameters['policyEvaluateRequest'] == null) {
            throw new runtime.RequiredError(
                'policyEvaluateRequest',
                'Required parameter "policyEvaluateRequest" was null or undefined when calling postPolicyEvaluate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/projects/{project_id}/policy/evaluate`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PolicyEvaluateRequestToJSON(requestParameters['policyEvaluateRequest']),
        };
    }

    /**
     * Policy evaluate (MVP)
     */
    async postPolicyEvaluateRaw(requestParameters: PostPolicyEvaluateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolicyEvaluateResponse>> {
        const requestOptions = await this.postPolicyEvaluateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PolicyEvaluateResponseFromJSON(jsonValue));
    }

    /**
     * Policy evaluate (MVP)
     */
    async postPolicyEvaluate(requestParameters: PostPolicyEvaluateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolicyEvaluateResponse> {
        const response = await this.postPolicyEvaluateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
