/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionRef
 */
export interface ActionRef {
    /**
     * 
     * @type {number}
     * @memberof ActionRef
     */
    actionId: number;
    /**
     * 
     * @type {string}
     * @memberof ActionRef
     */
    status: string;
}

/**
 * Check if a given object implements the ActionRef interface.
 */
export function instanceOfActionRef(value: object): value is ActionRef {
    if (!('actionId' in value) || value['actionId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ActionRefFromJSON(json: any): ActionRef {
    return ActionRefFromJSONTyped(json, false);
}

export function ActionRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionRef {
    if (json == null) {
        return json;
    }
    return {
        
        'actionId': json['action_id'],
        'status': json['status'],
    };
}

export function ActionRefToJSON(json: any): ActionRef {
    return ActionRefToJSONTyped(json, false);
}

export function ActionRefToJSONTyped(value?: ActionRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action_id': value['actionId'],
        'status': value['status'],
    };
}

