/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecisionProposeResponse
 */
export interface DecisionProposeResponse {
    /**
     * 
     * @type {number}
     * @memberof DecisionProposeResponse
     */
    decisionId: number;
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeResponse
     */
    decisionKey: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeResponse
     */
    traceId: string;
}

/**
 * Check if a given object implements the DecisionProposeResponse interface.
 */
export function instanceOfDecisionProposeResponse(value: object): value is DecisionProposeResponse {
    if (!('decisionId' in value) || value['decisionId'] === undefined) return false;
    if (!('decisionKey' in value) || value['decisionKey'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    return true;
}

export function DecisionProposeResponseFromJSON(json: any): DecisionProposeResponse {
    return DecisionProposeResponseFromJSONTyped(json, false);
}

export function DecisionProposeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionProposeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'decisionId': json['decision_id'],
        'decisionKey': json['decision_key'],
        'status': json['status'],
        'traceId': json['trace_id'],
    };
}

export function DecisionProposeResponseToJSON(json: any): DecisionProposeResponse {
    return DecisionProposeResponseToJSONTyped(json, false);
}

export function DecisionProposeResponseToJSONTyped(value?: DecisionProposeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'decision_id': value['decisionId'],
        'decision_key': value['decisionKey'],
        'status': value['status'],
        'trace_id': value['traceId'],
    };
}

