/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecisionApproveRequest
 */
export interface DecisionApproveRequest {
    /**
     * 
     * @type {string}
     * @memberof DecisionApproveRequest
     */
    decidedById?: string;
}

/**
 * Check if a given object implements the DecisionApproveRequest interface.
 */
export function instanceOfDecisionApproveRequest(value: object): value is DecisionApproveRequest {
    return true;
}

export function DecisionApproveRequestFromJSON(json: any): DecisionApproveRequest {
    return DecisionApproveRequestFromJSONTyped(json, false);
}

export function DecisionApproveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionApproveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'decidedById': json['decided_by_id'] == null ? undefined : json['decided_by_id'],
    };
}

export function DecisionApproveRequestToJSON(json: any): DecisionApproveRequest {
    return DecisionApproveRequestToJSONTyped(json, false);
}

export function DecisionApproveRequestToJSONTyped(value?: DecisionApproveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'decided_by_id': value['decidedById'],
    };
}

