/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecisionApproveResponse
 */
export interface DecisionApproveResponse {
    /**
     * 
     * @type {number}
     * @memberof DecisionApproveResponse
     */
    decisionId: number;
    /**
     * 
     * @type {string}
     * @memberof DecisionApproveResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionApproveResponse
     */
    traceId: string;
}

/**
 * Check if a given object implements the DecisionApproveResponse interface.
 */
export function instanceOfDecisionApproveResponse(value: object): value is DecisionApproveResponse {
    if (!('decisionId' in value) || value['decisionId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    return true;
}

export function DecisionApproveResponseFromJSON(json: any): DecisionApproveResponse {
    return DecisionApproveResponseFromJSONTyped(json, false);
}

export function DecisionApproveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionApproveResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'decisionId': json['decision_id'],
        'status': json['status'],
        'traceId': json['trace_id'],
    };
}

export function DecisionApproveResponseToJSON(json: any): DecisionApproveResponse {
    return DecisionApproveResponseToJSONTyped(json, false);
}

export function DecisionApproveResponseToJSONTyped(value?: DecisionApproveResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'decision_id': value['decisionId'],
        'status': value['status'],
        'trace_id': value['traceId'],
    };
}

