/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecisionProposeRequest
 */
export interface DecisionProposeRequest {
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeRequest
     */
    runId: string;
    /**
     * 
     * @type {number}
     * @memberof DecisionProposeRequest
     */
    policyEvaluationId: number;
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeRequest
     */
    subjectType: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeRequest
     */
    subjectId: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeRequest
     */
    decisionScope: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeRequest
     */
    policyVersionStr: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeRequest
     */
    pipelineVersion: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionProposeRequest
     */
    inputHash: string;
    /**
     * 
     * @type {number}
     * @memberof DecisionProposeRequest
     */
    inputsEvidenceAssetId: number;
    /**
     * 
     * @type {number}
     * @memberof DecisionProposeRequest
     */
    obligationsEvidenceAssetId: number;
}

/**
 * Check if a given object implements the DecisionProposeRequest interface.
 */
export function instanceOfDecisionProposeRequest(value: object): value is DecisionProposeRequest {
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('policyEvaluationId' in value) || value['policyEvaluationId'] === undefined) return false;
    if (!('subjectType' in value) || value['subjectType'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('decisionScope' in value) || value['decisionScope'] === undefined) return false;
    if (!('policyVersionStr' in value) || value['policyVersionStr'] === undefined) return false;
    if (!('pipelineVersion' in value) || value['pipelineVersion'] === undefined) return false;
    if (!('inputHash' in value) || value['inputHash'] === undefined) return false;
    if (!('inputsEvidenceAssetId' in value) || value['inputsEvidenceAssetId'] === undefined) return false;
    if (!('obligationsEvidenceAssetId' in value) || value['obligationsEvidenceAssetId'] === undefined) return false;
    return true;
}

export function DecisionProposeRequestFromJSON(json: any): DecisionProposeRequest {
    return DecisionProposeRequestFromJSONTyped(json, false);
}

export function DecisionProposeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionProposeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['run_id'],
        'policyEvaluationId': json['policy_evaluation_id'],
        'subjectType': json['subject_type'],
        'subjectId': json['subject_id'],
        'decisionScope': json['decision_scope'],
        'policyVersionStr': json['policy_version_str'],
        'pipelineVersion': json['pipeline_version'],
        'inputHash': json['input_hash'],
        'inputsEvidenceAssetId': json['inputs_evidence_asset_id'],
        'obligationsEvidenceAssetId': json['obligations_evidence_asset_id'],
    };
}

export function DecisionProposeRequestToJSON(json: any): DecisionProposeRequest {
    return DecisionProposeRequestToJSONTyped(json, false);
}

export function DecisionProposeRequestToJSONTyped(value?: DecisionProposeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['runId'],
        'policy_evaluation_id': value['policyEvaluationId'],
        'subject_type': value['subjectType'],
        'subject_id': value['subjectId'],
        'decision_scope': value['decisionScope'],
        'policy_version_str': value['policyVersionStr'],
        'pipeline_version': value['pipelineVersion'],
        'input_hash': value['inputHash'],
        'inputs_evidence_asset_id': value['inputsEvidenceAssetId'],
        'obligations_evidence_asset_id': value['obligationsEvidenceAssetId'],
    };
}

