/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecisionApplyRequest
 */
export interface DecisionApplyRequest {
    /**
     * 
     * @type {string}
     * @memberof DecisionApplyRequest
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionApplyRequest
     */
    actionType?: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionApplyRequest
     */
    actionScope?: string;
    /**
     * 
     * @type {number}
     * @memberof DecisionApplyRequest
     */
    targetEvidenceAssetId: number;
    /**
     * 
     * @type {number}
     * @memberof DecisionApplyRequest
     */
    planEvidenceAssetId: number;
    /**
     * 
     * @type {string}
     * @memberof DecisionApplyRequest
     */
    budgetCurrency?: string;
    /**
     * 
     * @type {number}
     * @memberof DecisionApplyRequest
     */
    budgetEstimateAmount?: number;
}

/**
 * Check if a given object implements the DecisionApplyRequest interface.
 */
export function instanceOfDecisionApplyRequest(value: object): value is DecisionApplyRequest {
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('targetEvidenceAssetId' in value) || value['targetEvidenceAssetId'] === undefined) return false;
    if (!('planEvidenceAssetId' in value) || value['planEvidenceAssetId'] === undefined) return false;
    return true;
}

export function DecisionApplyRequestFromJSON(json: any): DecisionApplyRequest {
    return DecisionApplyRequestFromJSONTyped(json, false);
}

export function DecisionApplyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionApplyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['run_id'],
        'actionType': json['action_type'] == null ? undefined : json['action_type'],
        'actionScope': json['action_scope'] == null ? undefined : json['action_scope'],
        'targetEvidenceAssetId': json['target_evidence_asset_id'],
        'planEvidenceAssetId': json['plan_evidence_asset_id'],
        'budgetCurrency': json['budget_currency'] == null ? undefined : json['budget_currency'],
        'budgetEstimateAmount': json['budget_estimate_amount'] == null ? undefined : json['budget_estimate_amount'],
    };
}

export function DecisionApplyRequestToJSON(json: any): DecisionApplyRequest {
    return DecisionApplyRequestToJSONTyped(json, false);
}

export function DecisionApplyRequestToJSONTyped(value?: DecisionApplyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['runId'],
        'action_type': value['actionType'],
        'action_scope': value['actionScope'],
        'target_evidence_asset_id': value['targetEvidenceAssetId'],
        'plan_evidence_asset_id': value['planEvidenceAssetId'],
        'budget_currency': value['budgetCurrency'],
        'budget_estimate_amount': value['budgetEstimateAmount'],
    };
}

