/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActionRef } from './ActionRef';
import {
    ActionRefFromJSON,
    ActionRefFromJSONTyped,
    ActionRefToJSON,
    ActionRefToJSONTyped,
} from './ActionRef';

/**
 * 
 * @export
 * @interface DecisionApplyResponse
 */
export interface DecisionApplyResponse {
    /**
     * 
     * @type {string}
     * @memberof DecisionApplyResponse
     */
    traceId: string;
    /**
     * 
     * @type {number}
     * @memberof DecisionApplyResponse
     */
    decisionId: number;
    /**
     * 
     * @type {string}
     * @memberof DecisionApplyResponse
     */
    decisionStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionApplyResponse
     */
    decisionKind?: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionApplyResponse
     */
    blockedReason?: string;
    /**
     * 
     * @type {Array<ActionRef>}
     * @memberof DecisionApplyResponse
     */
    actions: Array<ActionRef>;
}

/**
 * Check if a given object implements the DecisionApplyResponse interface.
 */
export function instanceOfDecisionApplyResponse(value: object): value is DecisionApplyResponse {
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    if (!('decisionId' in value) || value['decisionId'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function DecisionApplyResponseFromJSON(json: any): DecisionApplyResponse {
    return DecisionApplyResponseFromJSONTyped(json, false);
}

export function DecisionApplyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionApplyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'traceId': json['trace_id'],
        'decisionId': json['decision_id'],
        'decisionStatus': json['decision_status'] == null ? undefined : json['decision_status'],
        'decisionKind': json['decision_kind'] == null ? undefined : json['decision_kind'],
        'blockedReason': json['blocked_reason'] == null ? undefined : json['blocked_reason'],
        'actions': ((json['actions'] as Array<any>).map(ActionRefFromJSON)),
    };
}

export function DecisionApplyResponseToJSON(json: any): DecisionApplyResponse {
    return DecisionApplyResponseToJSONTyped(json, false);
}

export function DecisionApplyResponseToJSONTyped(value?: DecisionApplyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trace_id': value['traceId'],
        'decision_id': value['decisionId'],
        'decision_status': value['decisionStatus'],
        'decision_kind': value['decisionKind'],
        'blocked_reason': value['blockedReason'],
        'actions': ((value['actions'] as Array<any>).map(ActionRefToJSON)),
    };
}

