/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseError
 */
export interface ErrorResponseError {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    traceId: string;
}

/**
 * Check if a given object implements the ErrorResponseError interface.
 */
export function instanceOfErrorResponseError(value: object): value is ErrorResponseError {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    return true;
}

export function ErrorResponseErrorFromJSON(json: any): ErrorResponseError {
    return ErrorResponseErrorFromJSONTyped(json, false);
}

export function ErrorResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'message': json['message'],
        'traceId': json['trace_id'],
    };
}

export function ErrorResponseErrorToJSON(json: any): ErrorResponseError {
    return ErrorResponseErrorToJSONTyped(json, false);
}

export function ErrorResponseErrorToJSONTyped(value?: ErrorResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'message': value['message'],
        'trace_id': value['traceId'],
    };
}

