/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvidenceAsset
 */
export interface EvidenceAsset {
    /**
     * 
     * @type {number}
     * @memberof EvidenceAsset
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EvidenceAsset
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof EvidenceAsset
     */
    evidenceRef: string;
    /**
     * 
     * @type {EvidenceAssetMediaTypeEnum}
     * @memberof EvidenceAsset
     */
    mediaType: EvidenceAssetMediaTypeEnum;
    /**
     * 
     * @type {EvidenceAssetSourceKindEnum}
     * @memberof EvidenceAsset
     */
    sourceKind: EvidenceAssetSourceKindEnum;
    /**
     * 
     * @type {string}
     * @memberof EvidenceAsset
     */
    sourceUri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EvidenceAsset
     */
    contentSha256: string;
    /**
     * 
     * @type {number}
     * @memberof EvidenceAsset
     */
    contentLength: number;
    /**
     * 
     * @type {string}
     * @memberof EvidenceAsset
     */
    mimeType: string;
    /**
     * 
     * @type {string}
     * @memberof EvidenceAsset
     */
    language?: string | null;
    /**
     * 
     * @type {EvidenceAssetRetentionPolicyEnum}
     * @memberof EvidenceAsset
     */
    retentionPolicy: EvidenceAssetRetentionPolicyEnum;
    /**
     * 
     * @type {Date}
     * @memberof EvidenceAsset
     */
    expiresAtUtc?: Date | null;
    /**
     * 
     * @type {EvidenceAssetStatusEnum}
     * @memberof EvidenceAsset
     */
    status: EvidenceAssetStatusEnum;
    /**
     * 
     * @type {EvidenceAssetCreatedByTypeEnum}
     * @memberof EvidenceAsset
     */
    createdByType: EvidenceAssetCreatedByTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EvidenceAsset
     */
    createdById?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EvidenceAsset
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EvidenceAsset
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const EvidenceAssetMediaTypeEnum = {
    Text: 'text',
    Image: 'image',
    Audio: 'audio',
    Video: 'video',
    Binary: 'binary'
} as const;
export type EvidenceAssetMediaTypeEnum = typeof EvidenceAssetMediaTypeEnum[keyof typeof EvidenceAssetMediaTypeEnum];

/**
 * @export
 */
export const EvidenceAssetSourceKindEnum = {
    PisagFetch: 'pisag_fetch',
    Upload: 'upload',
    Webhook: 'webhook',
    Generated: 'generated',
    Import: 'import'
} as const;
export type EvidenceAssetSourceKindEnum = typeof EvidenceAssetSourceKindEnum[keyof typeof EvidenceAssetSourceKindEnum];

/**
 * @export
 */
export const EvidenceAssetRetentionPolicyEnum = {
    Short: 'short',
    Standard: 'standard',
    LegalHold: 'legal_hold'
} as const;
export type EvidenceAssetRetentionPolicyEnum = typeof EvidenceAssetRetentionPolicyEnum[keyof typeof EvidenceAssetRetentionPolicyEnum];

/**
 * @export
 */
export const EvidenceAssetStatusEnum = {
    Active: 'active',
    Expired: 'expired',
    Tombstoned: 'tombstoned'
} as const;
export type EvidenceAssetStatusEnum = typeof EvidenceAssetStatusEnum[keyof typeof EvidenceAssetStatusEnum];

/**
 * @export
 */
export const EvidenceAssetCreatedByTypeEnum = {
    System: 'system',
    User: 'user',
    Service: 'service'
} as const;
export type EvidenceAssetCreatedByTypeEnum = typeof EvidenceAssetCreatedByTypeEnum[keyof typeof EvidenceAssetCreatedByTypeEnum];


/**
 * Check if a given object implements the EvidenceAsset interface.
 */
export function instanceOfEvidenceAsset(value: object): value is EvidenceAsset {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('evidenceRef' in value) || value['evidenceRef'] === undefined) return false;
    if (!('mediaType' in value) || value['mediaType'] === undefined) return false;
    if (!('sourceKind' in value) || value['sourceKind'] === undefined) return false;
    if (!('contentSha256' in value) || value['contentSha256'] === undefined) return false;
    if (!('contentLength' in value) || value['contentLength'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('retentionPolicy' in value) || value['retentionPolicy'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdByType' in value) || value['createdByType'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EvidenceAssetFromJSON(json: any): EvidenceAsset {
    return EvidenceAssetFromJSONTyped(json, false);
}

export function EvidenceAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvidenceAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'evidenceRef': json['evidence_ref'],
        'mediaType': json['media_type'],
        'sourceKind': json['source_kind'],
        'sourceUri': json['source_uri'] == null ? undefined : json['source_uri'],
        'contentSha256': json['content_sha256'],
        'contentLength': json['content_length'],
        'mimeType': json['mime_type'],
        'language': json['language'] == null ? undefined : json['language'],
        'retentionPolicy': json['retention_policy'],
        'expiresAtUtc': json['expires_at_utc'] == null ? undefined : (new Date(json['expires_at_utc'])),
        'status': json['status'],
        'createdByType': json['created_by_type'],
        'createdById': json['created_by_id'] == null ? undefined : json['created_by_id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function EvidenceAssetToJSON(json: any): EvidenceAsset {
    return EvidenceAssetToJSONTyped(json, false);
}

export function EvidenceAssetToJSONTyped(value?: EvidenceAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'evidence_ref': value['evidenceRef'],
        'media_type': value['mediaType'],
        'source_kind': value['sourceKind'],
        'source_uri': value['sourceUri'],
        'content_sha256': value['contentSha256'],
        'content_length': value['contentLength'],
        'mime_type': value['mimeType'],
        'language': value['language'],
        'retention_policy': value['retentionPolicy'],
        'expires_at_utc': value['expiresAtUtc'] == null ? value['expiresAtUtc'] : value['expiresAtUtc'].toISOString(),
        'status': value['status'],
        'created_by_type': value['createdByType'],
        'created_by_id': value['createdById'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

