/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LedgerIngestRun
 */
export interface LedgerIngestRun {
    /**
     * 
     * @type {string}
     * @memberof LedgerIngestRun
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LedgerIngestRun
     */
    projectId: string;
    /**
     * 
     * @type {LedgerIngestRunModeEnum}
     * @memberof LedgerIngestRun
     */
    mode: LedgerIngestRunModeEnum;
    /**
     * Present when mode=single_event.
     * @type {string}
     * @memberof LedgerIngestRun
     */
    sourceEventKey?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof LedgerIngestRun
     */
    fromTs?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof LedgerIngestRun
     */
    toTs?: Date | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LedgerIngestRun
     */
    filter: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof LedgerIngestRun
     */
    idempotencyKey: string;
    /**
     * 
     * @type {LedgerIngestRunStatusEnum}
     * @memberof LedgerIngestRun
     */
    status: LedgerIngestRunStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LedgerIngestRun
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof LedgerIngestRun
     */
    traceId: string;
    /**
     * 
     * @type {string}
     * @memberof LedgerIngestRun
     */
    policyVersionId: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LedgerIngestRun
     */
    stats: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof LedgerIngestRun
     */
    evidenceRefs: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof LedgerIngestRun
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof LedgerIngestRun
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const LedgerIngestRunModeEnum = {
    SingleEvent: 'single_event',
    Range: 'range'
} as const;
export type LedgerIngestRunModeEnum = typeof LedgerIngestRunModeEnum[keyof typeof LedgerIngestRunModeEnum];

/**
 * @export
 */
export const LedgerIngestRunStatusEnum = {
    Accepted: 'accepted',
    Running: 'running',
    Succeeded: 'succeeded',
    FailedRecorded: 'failed_recorded'
} as const;
export type LedgerIngestRunStatusEnum = typeof LedgerIngestRunStatusEnum[keyof typeof LedgerIngestRunStatusEnum];


/**
 * Check if a given object implements the LedgerIngestRun interface.
 */
export function instanceOfLedgerIngestRun(value: object): value is LedgerIngestRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('filter' in value) || value['filter'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    if (!('policyVersionId' in value) || value['policyVersionId'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('evidenceRefs' in value) || value['evidenceRefs'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function LedgerIngestRunFromJSON(json: any): LedgerIngestRun {
    return LedgerIngestRunFromJSONTyped(json, false);
}

export function LedgerIngestRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerIngestRun {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'mode': json['mode'],
        'sourceEventKey': json['source_event_key'] == null ? undefined : json['source_event_key'],
        'fromTs': json['from_ts'] == null ? undefined : (new Date(json['from_ts'])),
        'toTs': json['to_ts'] == null ? undefined : (new Date(json['to_ts'])),
        'filter': json['filter'],
        'idempotencyKey': json['idempotency_key'],
        'status': json['status'],
        'runId': json['run_id'],
        'traceId': json['trace_id'],
        'policyVersionId': json['policy_version_id'],
        'stats': json['stats'],
        'evidenceRefs': json['evidence_refs'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function LedgerIngestRunToJSON(json: any): LedgerIngestRun {
    return LedgerIngestRunToJSONTyped(json, false);
}

export function LedgerIngestRunToJSONTyped(value?: LedgerIngestRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'mode': value['mode'],
        'source_event_key': value['sourceEventKey'],
        'from_ts': value['fromTs'] == null ? value['fromTs'] : value['fromTs'].toISOString(),
        'to_ts': value['toTs'] == null ? value['toTs'] : value['toTs'].toISOString(),
        'filter': value['filter'],
        'idempotency_key': value['idempotencyKey'],
        'status': value['status'],
        'run_id': value['runId'],
        'trace_id': value['traceId'],
        'policy_version_id': value['policyVersionId'],
        'stats': value['stats'],
        'evidence_refs': value['evidenceRefs'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

