/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LedgerIngestRun } from './LedgerIngestRun';
import {
    LedgerIngestRunFromJSON,
    LedgerIngestRunFromJSONTyped,
    LedgerIngestRunToJSON,
    LedgerIngestRunToJSONTyped,
} from './LedgerIngestRun';

/**
 * 
 * @export
 * @interface LedgerIngestRunListResponse
 */
export interface LedgerIngestRunListResponse {
    /**
     * 
     * @type {Array<LedgerIngestRun>}
     * @memberof LedgerIngestRunListResponse
     */
    items: Array<LedgerIngestRun>;
}

/**
 * Check if a given object implements the LedgerIngestRunListResponse interface.
 */
export function instanceOfLedgerIngestRunListResponse(value: object): value is LedgerIngestRunListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function LedgerIngestRunListResponseFromJSON(json: any): LedgerIngestRunListResponse {
    return LedgerIngestRunListResponseFromJSONTyped(json, false);
}

export function LedgerIngestRunListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerIngestRunListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(LedgerIngestRunFromJSON)),
    };
}

export function LedgerIngestRunListResponseToJSON(json: any): LedgerIngestRunListResponse {
    return LedgerIngestRunListResponseToJSONTyped(json, false);
}

export function LedgerIngestRunListResponseToJSONTyped(value?: LedgerIngestRunListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(LedgerIngestRunToJSON)),
    };
}

