/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolicyEvaluateResponse
 */
export interface PolicyEvaluateResponse {
    /**
     * 
     * @type {string}
     * @memberof PolicyEvaluateResponse
     */
    inputHash: string;
    /**
     * 
     * @type {number}
     * @memberof PolicyEvaluateResponse
     */
    policyEvaluationId: number;
    /**
     * 
     * @type {string}
     * @memberof PolicyEvaluateResponse
     */
    result: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyEvaluateResponse
     */
    traceId: string;
}

/**
 * Check if a given object implements the PolicyEvaluateResponse interface.
 */
export function instanceOfPolicyEvaluateResponse(value: object): value is PolicyEvaluateResponse {
    if (!('inputHash' in value) || value['inputHash'] === undefined) return false;
    if (!('policyEvaluationId' in value) || value['policyEvaluationId'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    return true;
}

export function PolicyEvaluateResponseFromJSON(json: any): PolicyEvaluateResponse {
    return PolicyEvaluateResponseFromJSONTyped(json, false);
}

export function PolicyEvaluateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyEvaluateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'inputHash': json['input_hash'],
        'policyEvaluationId': json['policy_evaluation_id'],
        'result': json['result'],
        'traceId': json['trace_id'],
    };
}

export function PolicyEvaluateResponseToJSON(json: any): PolicyEvaluateResponse {
    return PolicyEvaluateResponseToJSONTyped(json, false);
}

export function PolicyEvaluateResponseToJSONTyped(value?: PolicyEvaluateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input_hash': value['inputHash'],
        'policy_evaluation_id': value['policyEvaluationId'],
        'result': value['result'],
        'trace_id': value['traceId'],
    };
}

