/* tslint:disable */
/* eslint-disable */
/**
 * AtlasKernel Platform API
 * Single Source of Contract (v24). Implementations must conform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolicyEvaluateRequest
 */
export interface PolicyEvaluateRequest {
    /**
     * 
     * @type {string}
     * @memberof PolicyEvaluateRequest
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyEvaluateRequest
     */
    policyVersionStr: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyEvaluateRequest
     */
    pipelineVersion: string;
    /**
     * 
     * @type {number}
     * @memberof PolicyEvaluateRequest
     */
    inputsEvidenceAssetId: number;
    /**
     * 
     * @type {number}
     * @memberof PolicyEvaluateRequest
     */
    reasonEvidenceAssetId: number;
    /**
     * 
     * @type {number}
     * @memberof PolicyEvaluateRequest
     */
    obligationsEvidenceAssetId: number;
}

/**
 * Check if a given object implements the PolicyEvaluateRequest interface.
 */
export function instanceOfPolicyEvaluateRequest(value: object): value is PolicyEvaluateRequest {
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('policyVersionStr' in value) || value['policyVersionStr'] === undefined) return false;
    if (!('pipelineVersion' in value) || value['pipelineVersion'] === undefined) return false;
    if (!('inputsEvidenceAssetId' in value) || value['inputsEvidenceAssetId'] === undefined) return false;
    if (!('reasonEvidenceAssetId' in value) || value['reasonEvidenceAssetId'] === undefined) return false;
    if (!('obligationsEvidenceAssetId' in value) || value['obligationsEvidenceAssetId'] === undefined) return false;
    return true;
}

export function PolicyEvaluateRequestFromJSON(json: any): PolicyEvaluateRequest {
    return PolicyEvaluateRequestFromJSONTyped(json, false);
}

export function PolicyEvaluateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyEvaluateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['run_id'],
        'policyVersionStr': json['policy_version_str'],
        'pipelineVersion': json['pipeline_version'],
        'inputsEvidenceAssetId': json['inputs_evidence_asset_id'],
        'reasonEvidenceAssetId': json['reason_evidence_asset_id'],
        'obligationsEvidenceAssetId': json['obligations_evidence_asset_id'],
    };
}

export function PolicyEvaluateRequestToJSON(json: any): PolicyEvaluateRequest {
    return PolicyEvaluateRequestToJSONTyped(json, false);
}

export function PolicyEvaluateRequestToJSONTyped(value?: PolicyEvaluateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['runId'],
        'policy_version_str': value['policyVersionStr'],
        'pipeline_version': value['pipelineVersion'],
        'inputs_evidence_asset_id': value['inputsEvidenceAssetId'],
        'reason_evidence_asset_id': value['reasonEvidenceAssetId'],
        'obligations_evidence_asset_id': value['obligationsEvidenceAssetId'],
    };
}

